// Auto-generated cross-language test vectors for lever-runner-carapace
// DO NOT EDIT — generated by validate_all.py from test-vectors.json

#[cfg(test)]
mod cross_language_tests {
    use super::*;
    use std::fs;

    const ACTIONS: &[&str] = &["north", "east", "south", "west"];

    #[test]
    fn test_blake2b_hashes() {
        assert_eq(
            blake2b_128(""),
            "cae66941d9efbd404e4d88758ea67670",
            "Hash mismatch for v0 ("") "
        );
        assert_eq(
            blake2b_128("hello"),
            "46fb7408d4f285228f4af516ea25851b",
            "Hash mismatch for v1 ("hello") "
        );
        assert_eq(
            blake2b_128("action:north"),
            "75d42cb75f1d04b6cdee14b8065041d0",
            "Hash mismatch for v2 ("action:north") "
        );
        assert_eq(
            blake2b_128("state:grid[3,7];prev:east"),
            "6aa1971ba80e2d9fbacb22c2315fe9f7",
            "Hash mismatch for v3 ("state:grid[3,7];prev:east") "
        );
        assert_eq(
            blake2b_128("state:grid[0,0];prev:null"),
            "5b5b877ed46336153f8580dd503f266a",
            "Hash mismatch for v4 ("state:grid[0,0];prev:null") "
        );
        assert_eq(
            blake2b_128("embed:test_positive"),
            "d88a6abce3406aca046bd863bc5ad34e",
            "Hash mismatch for v5 ("embed:test_positive") "
        );
        assert_eq(
            blake2b_128("embed:test_negative"),
            "690fa5aded3d16d3815e0dae479346bc",
            "Hash mismatch for v6 ("embed:test_negative") "
        );
        assert_eq(
            blake2b_128("gate:exact_match"),
            "2f0926c19e3836661b91ea93e57ca4ea",
            "Hash mismatch for v7 ("gate:exact_match") "
        );
        assert_eq(
            blake2b_128("gate:fuzzy_match"),
            "71cb317c174bd4d11909f6326cd71183",
            "Hash mismatch for v8 ("gate:fuzzy_match") "
        );
        assert_eq(
            blake2b_128("gate:semantic_miss"),
            "811277967e7e8064f8dedf5539c14ae5",
            "Hash mismatch for v9 ("gate:semantic_miss") "
        );
    }

    #[test]
    fn test_score_encoding() {
        {
            let scores: [f32; 4] = [0.5f32, 0.0f32, 0.0f32, 0.0f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "0000003f000000000000000000000000", "Score encoding mismatch for v0");
        }
        {
            let scores: [f32; 4] = [0.2f32, 1.0f32, 0.3f32, 0.0f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "cdcc4c3e0000803f9a99993e00000000", "Score encoding mismatch for v1");
        }
        {
            let scores: [f32; 4] = [0.5f32, 0.5f32, 0.5f32, 0.5f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "0000003f0000003f0000003f0000003f", "Score encoding mismatch for v2");
        }
        {
            let scores: [f32; 4] = [0.75f32, 3.14159f32, 0.0f32, 0.9f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "0000403fd00f4940000000006666663f", "Score encoding mismatch for v3");
        }
        {
            let scores: [f32; 4] = [0.0f32, 0.0f32, 0.0f32, 0.0f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "00000000000000000000000000000000", "Score encoding mismatch for v4");
        }
        {
            let scores: [f32; 4] = [1.0001f32, -1.0001f32, 0.0f32, 0.50000006f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "4703803f470380bf000000000100003f", "Score encoding mismatch for v5");
        }
        {
            let scores: [f32; 4] = [0.0f32, 0.0f32, 0.0f32, 1.0f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "0000000000000000000000000000803f", "Score encoding mismatch for v6");
        }
        {
            let scores: [f32; 4] = [9.8f32, 1.0f32, 0.0f32, 0.0f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "cdcc1c410000803f0000000000000000", "Score encoding mismatch for v7");
        }
        {
            let scores: [f32; 4] = [0.1f32, 0.1f32, 1.0f32, 0.1f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "cdcccc3dcdcccc3d0000803fcdcccc3d", "Score encoding mismatch for v8");
        }
        {
            let scores: [f32; 4] = [0.0f32, 0.0f32, 0.0f32, 0.0f32];
            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();
            assert_eq!(hex::encode(&bytes), "00000000000000000000000000000000", "Score encoding mismatch for v9");
        }
    }

    #[test]
    fn test_best_action() {
        {
            let scores: [f32; 4] = [0.5f32, 0.0f32, 0.0f32, 0.0f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let best = scores.iter().position(|&s| s == max).unwrap();
            assert_eq!(best, 0, "Best action mismatch for v0");
        }
        {
            let scores: [f32; 4] = [0.2f32, 1.0f32, 0.3f32, 0.0f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let best = scores.iter().position(|&s| s == max).unwrap();
            assert_eq!(best, 1, "Best action mismatch for v1");
        }
        {
            let scores: [f32; 4] = [0.5f32, 0.5f32, 0.5f32, 0.5f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let count = scores.iter().filter(|&&s| s == max).count();
            assert!(count > 1, "Expected tie for v2");
        }
        {
            let scores: [f32; 4] = [0.75f32, 3.14159f32, 0.0f32, 0.9f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let best = scores.iter().position(|&s| s == max).unwrap();
            assert_eq!(best, 1, "Best action mismatch for v3");
        }
        {
            let scores: [f32; 4] = [0.0f32, 0.0f32, 0.0f32, 0.0f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let count = scores.iter().filter(|&&s| s == max).count();
            assert!(count > 1, "Expected tie for v4");
        }
        {
            let scores: [f32; 4] = [1.0001f32, -1.0001f32, 0.0f32, 0.50000006f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let best = scores.iter().position(|&s| s == max).unwrap();
            assert_eq!(best, 0, "Best action mismatch for v5");
        }
        {
            let scores: [f32; 4] = [0.0f32, 0.0f32, 0.0f32, 1.0f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let best = scores.iter().position(|&s| s == max).unwrap();
            assert_eq!(best, 3, "Best action mismatch for v6");
        }
        {
            let scores: [f32; 4] = [9.8f32, 1.0f32, 0.0f32, 0.0f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let best = scores.iter().position(|&s| s == max).unwrap();
            assert_eq!(best, 0, "Best action mismatch for v7");
        }
        {
            let scores: [f32; 4] = [0.1f32, 0.1f32, 1.0f32, 0.1f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let best = scores.iter().position(|&s| s == max).unwrap();
            assert_eq!(best, 2, "Best action mismatch for v8");
        }
        {
            let scores: [f32; 4] = [0.0f32, 0.0f32, 0.0f32, 0.0f32];
            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
            let count = scores.iter().filter(|&&s| s == max).count();
            assert!(count > 1, "Expected tie for v9");
        }
    }

    #[test]
    fn test_wire_format_entry_size() {
        let n_actions: usize = 4;
        let metadata_len: usize = 0;
        let entry_size = 16 + 8 * n_actions + 4 + metadata_len;
        let entry_padded = (entry_size + 7) / 8 * 8;
        assert_eq!(entry_padded, 56, "Wire format entry size mismatch");
        let total = (64 + entry_padded + 255) / 256 * 256;
        assert_eq!(total, 256, "Wire format total padded mismatch");
    }
}
